### ISSUE TITLE
Yet another crash

### ISSUE THREAD

**Issue by ghost** [Zloool/manyfaced-honeypot#33]
![photo_2016-12-22_17-32-09](https://cloud.githubusercontent.com/assets/1379437/21428732/9767773a-c86c-11e6-8541-4032aef76b45.jpg)

**Comment by Zloool** [comment]
Fixed in https://github.com/Zloool/manyfaced-honeypot/commit/aee76247578ec479f96d3e93b1a349e21a6e25d9
